DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS quest;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE quest (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hero_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  FOREIGN KEY (hero_id) REFERENCES user (id)
);

CREATE TABLE objective (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quest_id INTEGER NOT NULL,
  description TEXT NOT NULL,
  completed BOOLEAN NOT NULL,
  FOREIGN KEY (quest_id) REFERENCES quest (id)
);
